services:

  service-a:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_METRICS_ENDPOINT: http://otel-collector:4317
      OTEL_LOG_LEVEL: DEBUG
      OTEL_TRACES_EXPORTER: console,otlp
      # OTEL_METRIC_EXPORT_INTERVAL: 1000 # ms


  service-b:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_METRICS_ENDPOINT: http://otel-collector:4317


  service-c:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_METRICS_ENDPOINT: http://otel-collector:4317


  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.jaeger.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317

  # an open-source tool for viewing traces locally
  jaeger:
    image: jaegertracing/all-in-one:1.21
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 16686:16686 # ui
      - 43177:4317   # http oltp
      - 14250:14250
  

# install docker "loki" plugin
# docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
