version: '3.8'

services:

  service-a:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOWNSTREAM_API_TARGETS: >-
        http://service-b:8000/echo?message=hi-service-b!,http://service-c:8000/echo?message=hi-service-c!
      # opentelemetry
      OTEL_PYTHON_LOG_CORRELATION: "true" # inject traces into logging library (with logging.basicConfig)
      OTEL_SERVICE_NAME: service-a
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  service-b:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOWNSTREAM_API_TARGETS: "" # This service won't hit another one
      # opentelemetry
      OTEL_PYTHON_LOG_CORRELATION: "true"
      OTEL_SERVICE_NAME: service-b
    volumes:
      - .:/app
    ports:
      - "8001:8000"

  service-c:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOWNSTREAM_API_TARGETS: "" # This service won't hit another one
      # opentelemetry
      OTEL_PYTHON_LOG_CORRELATION: "true"
      OTEL_SERVICE_NAME: service-c
    volumes:
      - .:/app
    ports:
      - "8002:8000"

  # hit service-a intermittently
  curl-client:
    image: busybox
    command: sh -c "sleep 3; while true; do wget -qO- http://service-a:8000/echo?message=hi-service-a!; sleep 10; done"
